package com.stefanenko.gitphone.data.exception

object DataBaseExceptionConstantStorage {
    const val DATA_BASE_ERROR = "DATA_BASE_ERROR"
    const val INSERT_ERROR = "INSERT_ERROR"
    const val DELETE_ERROR = "DELETE_ERROR"
    const val DELETE_ERROR_UNMATCHED_ID = "DELETE_ERROR_UNMATCHED_ID"
    const val NO_SUCH_USER_IN_DATABASE = "NO_SUCH_USER_IN_DATABASE"
    const val GET_USER_ERROR = "GET_USER_EXCEPTION"

}